name: CI
on:
  push:
    branches:
      - main
      - "!dependabot/**"
  pull_request:
  workflow_dispatch:
jobs:
  jest:
    name: Jest (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Node version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Npm Install
        run: npm ci
      - name: Run Jest
        run: npm run test:ci
      - name: Run Coveralls
        uses: coverallsapp/github-action@1.1.3
        if: matrix.node == '12'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/lcov.info
  flow:
    name: Flow type checking
    runs-on: ubuntu-latest
    steps:
        # Checkss out the repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Node
        uses: actions/setup-node@v2
        with:
          cache: npm
      - name: Npm Install
        run: npm ci
      - name: Flow type check
        run: npm run flow
  eslint:
    name: ESLint (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Node version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Npm Install
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  diff-breakUpAriaJSON:
    name: Compare JSON to src output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Node version
        uses: actions/setup-node@v2
        with:
          cache: npm
      - name: Npm Install
        run: npm ci
      - name: Run diff check for the breakUpAriaJSON script
        run: node scripts/breakUpAriaJSON.js && git diff --exit-code -- src
